import Head from 'next/head'
import { Inter } from 'next/font/google'
import LoginBtn from '@/components/login-btn'
import { getQuotes } from '@/lib/dbHelper'
import Quote from '@/components/quote'

const inter = Inter({ subsets: ['latin'] })

export async function getServerSideProps(context) {
    const quotes = await getQuotes(context.query);
    const data = JSON.stringify(quotes);

    return {
        props: {
            quotes: data,
        }
    }
}

export default function Home({ quotes }) {
    const json = JSON.parse(quotes);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <LoginBtn />
        {
            json.map((quote) => <Quote key={quote.id} quote={quote} />)
        }
      </main>
    </>
  )
}
