import Head from 'next/head'
import { Inter } from 'next/font/google'
import LoginBtn from '@/components/login-btn'
import { getQuotes } from '@/lib/dbHelper'

const inter = Inter({ subsets: ['latin'] })

export async function getServerSideProps(context) {
    const quotes = await getQuotes(context.query);
    const data = JSON.stringify(quotes);

    return {
        props: {
            quotes: data,
        }
    }
}

export default function Home({ quotes }) {
    const json = JSON.parse(quotes);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Hi :)</h1>
        <LoginBtn />
        {
            json.map((quote) => {
                return (
                    <div key={quote.id}>
                        <h2>{quote.date}</h2>
                        <ul>
                            {
                                quote.lines.map((line) => {
                                    return (
                                        <li key={line.id}>
                                            <p>{ line.author ? line.author.name : line.authorAlias}: {line.line}</p>
                                            <p></p>
                                        </li>
                                    )
                                })
                            }
                        </ul>
                    </div>
                )
            })
        }
      </main>
    </>
  )
}
